"""Generate an Abaqus/Standard input deck for the 3D DCB specimen using the *exact same
hexahedral mesh* (node coordinates + hex/cohesive connectivity) as diffcohesive's own
``build_double_cantilever_mesh_3d``, so the comparison in compare_abaqus_3d.py is an
apples-to-apples check of the 3D element stack, not of two independently built meshes.

Bulk arms -> C3D8 (8-node trilinear hexahedra; the same nominal element technology as the
model's own hexes -- both shear-lock identically in slender bending, which is the point of
same-mesh comparison). Cohesive ligament -> COH3D8 (8-node 3D cohesive elements): our
connectivity [b0..b3, t0..t3] with t_i coincident above b_i maps one-to-one onto Abaqus's
COH3D8 node order (bottom face 1-4, top face 5-8), so no reordering is needed. The
traction-separation response maps from the same BilinearMixedModeTSL parameters as
tests/assembly/test_dcb_3d.py: elastic traction stiffness = K, QUADS initiation =
(T_max_n, T_max_s, T_max_s), BK energy-based linear-softening evolution = (G_c1, G_c2, eta).

Boundary conditions match the diffcohesive run: the x = L face is fully clamped, and the two
tip node lines (x = 0, y = 0 and y = 2*arm_height, all z) are opened by +/- MAX_DISP/2 in y.

Run with (from repo root, any Python environment -- this script only writes plain text):
    python abaqus/dcb3d/generate_inp_3d.py
Then solve with Abaqus itself:
    & "C:\\SIMULIA\\Commands\\abaqus.bat" job=dcb3d input=dcb3d.inp interactive
"""

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from diffcohesive.mesh import build_double_cantilever_mesh_3d

HERE = Path(__file__).resolve().parent

# Geometry/material/law: identical to tests/assembly/test_dcb_3d.py and run_diffcohesive_3d.py.
L, ARM, W, A0 = 60.0, 2.0, 4.0, 20.0
NX, NY, NZ = 30, 2, 2
E, NU = 70000.0, 0.3
SIGMA0, GC, K, ETA = 30.0, 0.5, 1.0e4, 1.0

MAX_DISP = 2.5   # total opening (tip separation), traced under automatic incrementation
N_STEPS_ABQ = 25


def main():
    mesh = build_double_cantilever_mesh_3d(L, ARM, W, A0, nx=NX, ny=NY, nz=NZ)
    points = mesh.points.tolist()
    hexes = mesh.elements.tolist()
    coh = mesh.cohesive_connectivity.tolist()
    right_nodes = mesh.right_edge_nodes.tolist()
    tip_top = mesh.tip_top_nodes.tolist()
    tip_bottom = mesh.tip_bottom_nodes.tolist()

    lines = []
    lines.append("*HEADING")
    lines.append("3D DCB mode-I reference model, mesh generated by diffcohesive/mesh/specimens.py")
    lines.append("**")
    lines.append("*NODE")
    for i, (x, y, z) in enumerate(points, start=1):
        lines.append(f"{i}, {x:.10f}, {y:.10f}, {z:.10f}")

    lines.append("**")
    lines.append("*ELEMENT, TYPE=C3D8, ELSET=ARMS")
    for i, conn in enumerate(hexes, start=1):
        lines.append(f"{i}, " + ", ".join(str(n + 1) for n in conn))

    n_bulk = len(hexes)
    lines.append("**")
    lines.append("*ELEMENT, TYPE=COH3D8, ELSET=COHESIVE")
    for i, conn in enumerate(coh, start=n_bulk + 1):
        lines.append(f"{i}, " + ", ".join(str(n + 1) for n in conn))

    lines.append("**")
    lines.append("*SOLID SECTION, ELSET=ARMS, MATERIAL=ARM_MAT")
    lines.append(",")
    lines.append("*COHESIVE SECTION, ELSET=COHESIVE, MATERIAL=COH_MAT, RESPONSE=TRACTION SEPARATION, THICKNESS=SPECIFIED")
    lines.append("1.0")

    lines.append("**")
    lines.append("*MATERIAL, NAME=ARM_MAT")
    lines.append("*ELASTIC")
    lines.append(f"{E}, {NU}")

    lines.append("**")
    lines.append("*MATERIAL, NAME=COH_MAT")
    lines.append("*ELASTIC, TYPE=TRACTION")
    lines.append(f"{K}, {K}, {K}")
    lines.append("*DAMAGE INITIATION, CRITERION=QUADS")
    lines.append(f"{SIGMA0}, {SIGMA0}, {SIGMA0}")
    lines.append(f"*DAMAGE EVOLUTION, TYPE=ENERGY, MIXED MODE BEHAVIOR=BK, SOFTENING=LINEAR, POWER={ETA}")
    lines.append(f"{GC}, {GC}, {GC}")

    lines.append("**")
    lines.append("*NSET, NSET=RIGHT_FACE")
    for k in range(0, len(right_nodes), 12):
        lines.append(", ".join(str(n + 1) for n in right_nodes[k:k + 12]))
    lines.append("*NSET, NSET=TIP_TOP")
    lines.append(", ".join(str(n + 1) for n in tip_top))
    lines.append("*NSET, NSET=TIP_BOTTOM")
    lines.append(", ".join(str(n + 1) for n in tip_bottom))

    lines.append("**")
    lines.append("*STEP, NAME=OPEN, NLGEOM=NO, INC=2000")
    lines.append("*STATIC")
    lines.append(f"{MAX_DISP / N_STEPS_ABQ / 10:.6f}, {MAX_DISP:.6f}, 1e-10, {MAX_DISP / N_STEPS_ABQ:.6f}")
    lines.append("*BOUNDARY")
    lines.append("RIGHT_FACE, 1, 3, 0.0")
    lines.append(f"TIP_TOP, 2, 2, {MAX_DISP / 2:.6f}")
    lines.append(f"TIP_BOTTOM, 2, 2, {-MAX_DISP / 2:.6f}")
    lines.append("*OUTPUT, FIELD, FREQUENCY=5")
    lines.append("*NODE OUTPUT")
    lines.append("U, RF")
    lines.append("*ELEMENT OUTPUT, ELSET=COHESIVE")
    lines.append("SDEG")
    lines.append("*OUTPUT, HISTORY, FREQUENCY=1")
    lines.append("*NODE OUTPUT, NSET=TIP_TOP")
    lines.append("U2, RF2")
    lines.append("*NODE OUTPUT, NSET=TIP_BOTTOM")
    lines.append("U2, RF2")
    lines.append("*END STEP")

    (HERE / "dcb3d.inp").write_text("\n".join(lines) + "\n")

    # Tip node labels (1-based) for extract_odb_3d.py, which runs under Abaqus's own Python
    # and cannot import this repo.
    with open(HERE / "dcb3d_meta.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["set", "labels"])
        w.writerow(["tip_top", " ".join(str(n + 1) for n in tip_top)])
        w.writerow(["tip_bottom", " ".join(str(n + 1) for n in tip_bottom)])

    print(f"Wrote dcb3d.inp ({len(points)} nodes, {n_bulk} C3D8, {len(coh)} COH3D8) and dcb3d_meta.csv")


if __name__ == "__main__":
    main()
