"""Generate an Abaqus/Standard input deck for the DCB specimen using the *exact same mesh*
(node coordinates + triangle/cohesive connectivity) as diffcohesive's own
``build_double_cantilever_mesh``, so the comparison in compare_abaqus.py is a true apples-to-
apples check of the physics/solver, not of two independently-built meshes.

Bulk arms -> CPE3 (3-node plane strain triangles, matching our own triangular mesh exactly).
Cohesive ligament -> COH2D4 (4-node 2D cohesive elements), traction-separation response mapped
directly from the same BilinearMixedModeTSL parameters used in examples/dcb.py: elastic
traction stiffness = K, QUADS damage initiation = (T_max_n, T_max_s), BK mixed-mode energy-based
linear-softening damage evolution = (G_c1, G_c2, eta). Abaqus's COH2D4 node order (N1,N2 bottom
face left-to-right, N3 directly above N2, N4 directly above N1) matches our own cohesive
connectivity convention [a_bottom, b_bottom, b_top, a_top] exactly (zero-thickness coincident
top/bottom nodes), so no reordering is needed.

Run with (from repo root, any Python environment -- this script only writes plain text):
    python abaqus/dcb/generate_inp.py
Then solve with Abaqus itself (not this environment's Python):
    & "C:\\SIMULIA\\Commands\\abaqus.bat" job=dcb_ref input=abaqus/dcb/dcb.inp interactive
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from examples.dcb import DEFAULT_PARAMS
from diffcohesive.mesh import build_double_cantilever_mesh

OUT_PATH = Path(__file__).resolve().parent / "dcb.inp"

# Displacement steps: match examples/dcb.py's default sweep closely enough for a meaningful
# comparison (Abaqus uses its own automatic time incrementation within each step).
MAX_DISP = 0.6
N_STEPS_ABQ = 20  # coarser outer steps; Abaqus subdivides automatically via *STATIC increments


def main(riks: bool = False):
    p = DEFAULT_PARAMS
    mesh = build_double_cantilever_mesh(
        p["length"], p["arm_height"], p["crack_length"], p["nx"], p["ny"]
    )
    points = mesh.points.tolist()
    elements = mesh.elements.tolist()
    coh = mesh.cohesive_connectivity.tolist()

    right_nodes = mesh.right_edge_nodes.tolist()
    tip_top = mesh.tip_top
    tip_bottom = mesh.tip_bottom

    lines = []
    lines.append("*HEADING")
    lines.append("DCB mode-I reference model, mesh generated by diffcohesive/mesh/specimens.py")
    lines.append("**")
    lines.append("*NODE")
    for i, (x, y) in enumerate(points, start=1):
        lines.append(f"{i}, {x:.10f}, {y:.10f}")

    lines.append("**")
    lines.append("*ELEMENT, TYPE=CPE3, ELSET=ARMS")
    for i, (n1, n2, n3) in enumerate(elements, start=1):
        lines.append(f"{i}, {n1 + 1}, {n2 + 1}, {n3 + 1}")

    n_bulk = len(elements)
    lines.append("**")
    lines.append("*ELEMENT, TYPE=COH2D4, ELSET=COHESIVE")
    for i, (a_bot, b_bot, b_top, a_top) in enumerate(coh, start=n_bulk + 1):
        lines.append(f"{i}, {a_bot + 1}, {b_bot + 1}, {b_top + 1}, {a_top + 1}")

    lines.append("**")
    lines.append("*SOLID SECTION, ELSET=ARMS, MATERIAL=ARM_MAT")
    lines.append("1.0")
    lines.append("*COHESIVE SECTION, ELSET=COHESIVE, MATERIAL=COH_MAT, RESPONSE=TRACTION SEPARATION, THICKNESS=SPECIFIED")
    lines.append("1.0")

    lines.append("**")
    lines.append("*MATERIAL, NAME=ARM_MAT")
    lines.append("*ELASTIC")
    lines.append(f"{p['E']}, {p['nu']}")

    lines.append("**")
    lines.append("*MATERIAL, NAME=COH_MAT")
    lines.append("*ELASTIC, TYPE=TRACTION")
    lines.append(f"{p['K']}, {p['K']}, {p['K']}")
    lines.append("*DAMAGE INITIATION, CRITERION=QUADS")
    lines.append(f"{p['T_max_n']}, {p['T_max_s']}, {p['T_max_s']}")
    eta = p["eta"] if "eta" in p else 1.0
    lines.append(f"*DAMAGE EVOLUTION, TYPE=ENERGY, MIXED MODE BEHAVIOR=BK, SOFTENING=LINEAR, POWER={eta}")
    lines.append(f"{p['G_c1']}, {p['G_c2']}, {p['G_c2']}")

    lines.append("**")
    lines.append("*NSET, NSET=RIGHT_EDGE")
    lines.append(", ".join(str(n + 1) for n in right_nodes))
    lines.append("*NSET, NSET=TIP_TOP")
    lines.append(f"{tip_top + 1}")
    lines.append("*NSET, NSET=TIP_BOTTOM")
    lines.append(f"{tip_bottom + 1}")

    lines.append("**")
    lines.append("*STEP, NAME=OPEN, NLGEOM=NO, INC=1000")
    if riks:
        # Riks arc-length continuation: prescribed displacements are scaled by the load
        # proportionality factor; terminate when the top tip's u2 reaches ~1.2x the reference
        # value (so the traced path covers the same opening range as the *STATIC run).
        lines.append("*STATIC, RIKS")
        lines.append(f"0.03, 1.0, 1e-08, 0.08, 1.5, {tip_top + 1}, 2, {0.6 * MAX_DISP:.6f}")
    else:
        lines.append("*STATIC")
        lines.append(f"{MAX_DISP / N_STEPS_ABQ / 10:.6f}, {MAX_DISP:.6f}, 1e-08, {MAX_DISP / N_STEPS_ABQ:.6f}")
    lines.append("*BOUNDARY")
    lines.append("RIGHT_EDGE, 1, 2, 0.0")
    lines.append(f"TIP_TOP, 2, 2, {MAX_DISP / 2:.6f}")
    lines.append(f"TIP_BOTTOM, 2, 2, {-MAX_DISP / 2:.6f}")
    lines.append("*OUTPUT, FIELD, FREQUENCY=1")
    lines.append("*NODE OUTPUT")
    lines.append("U, RF")
    lines.append("*ELEMENT OUTPUT, ELSET=COHESIVE")
    lines.append("SDEG, DMICRT")
    lines.append("*OUTPUT, HISTORY, FREQUENCY=1")
    lines.append("*NODE OUTPUT, NSET=TIP_TOP")
    lines.append("U2, RF2")
    lines.append("*NODE OUTPUT, NSET=TIP_BOTTOM")
    lines.append("U2, RF2")
    lines.append("*END STEP")

    out = OUT_PATH.with_name("dcb_riks.inp") if riks else OUT_PATH
    out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out} ({len(points)} nodes, {n_bulk} bulk CPE3, {len(coh)} COH2D4)")


if __name__ == "__main__":
    import sys

    main(riks="--riks" in sys.argv)
